---
title: "Debris analysis using soupX"
output:
  html_document: default
  pdf_document: default
---


```{r}
library(dplyr)
library(Seurat)
library(SC3)
library(SingleCellExperiment)
#install.packages("githubinstall")
#library(githubinstall)
#githubinstall("scmap")
library(scmap)
#devtools::install_github("constantAmateur/SoupX")
library(SoupX)
library(ggplot2)

```

The starting point is to download the raw and filtered cellranger output and extract them to a folder.
#Loading the data
SoupX comes with a convenience function for loading 10X data processed using cellranger.


#Quantify debris as droplets containing 3-100 nUMI

```{r}
samples=read.csv("/home/jovyan/tisstab/analysis/allsamples.csv")
#Exclude bad sample
samples=samples[samples$sample!="HCATisStabAug177276393",]

nDrop.all=data.frame(nUMI=numeric(),Donor=character(), Time=character, sample.id=character(), Tissue=character())

for (i in 1:nrow(samples)){
  dataDirs = c(paste0("/home/jovyan/tisstab/data/", samples$sample[i]))
  scl = load10X(dataDirs, keepDroplets = TRUE)
  scl$channels$Channel1 = estimateSoup(scl$channels$Channel1)
  nDrop=as.data.frame(scl$channels$Channel1$nDropUMIs[((scl$channels$Channel1$nDropUMIs <=100)& (scl$channels$Channel1$nDropUMIs>1))])
  colnames(nDrop)="nUMI"
  nDrop$Donor=samples$patient[i]
  nDrop$Time=samples$timepoint[i]
  nDrop$sample.id=samples$sample[i]
  nDrop$Tissue=samples$organ[i]
  nDrop.all=rbind(nDrop.all, nDrop)
}

saveRDS(nDrop.all, "/home/jovyan/tisstab/analysis/soupX.nDropUMI.rds")

```



```{r}

timecolors=readRDS("/home/jovyan/tisstab/timecolors.rds" )
donorcolors=readRDS("/home/jovyan/tisstab/donorcolors.rds")

nDrop.all=readRDS( "/home/jovyan/tisstab/analysis/soupX.nDropUMI.rds")
nDrop=nDrop.all[nDrop.all$Tissue=="Spleen",]


ggplot(nDrop, aes(x=Donor, y=nUMI, fill=Time)) +
geom_boxplot(outlier.shape=".")+
  theme_classic()+  scale_fill_manual(values=timecolors)+ theme_classic()
  
ggplot(nDrop, aes(x=Time, y=nUMI, fill=Donor)) +
geom_boxplot(outlier.shape=".")+
  theme_classic()+    scale_fill_manual(values=donorcolors[1:5])+ theme_classic()


#All tissues
samples$mean=0
samples$median=0
samples$q75=0
samples$stdev=0
for (i in (1:nrow(samples))){
  mea=mean(nDrop.all$nUMI[nDrop.all$sample==samples$sample[i]])
  samples$mean[i]=mea
  quant=quantile(nDrop.all$nUMI[nDrop.all$sample==samples$sample[i]], c(.5, .75))
  samples$median[i]=quant[1]
  samples$q75[i]=quant[2]
  samples$stdev[i]=sd(nDrop.all$nUMI[nDrop.all$sample==samples$sample[i]])

}

samples$organ_donor=paste(samples$organ, samples$patient, sep="_")

ggplot(samples, aes(x=timepoint, y=mean, group=organ_donor)) +
  geom_point(aes(color=organ, size=3))+
  ggtitle("Mean debris nUMI")+
  geom_line(linetype="dashed" , color="grey", size=0.9)




alldata=samples

#Spleen only
samples=alldata[alldata$organ=="Spleen",]
ggplot(samples, aes(x=timepoint, y=mean, group=patient)) +
  geom_line(aes(linetype=patient), size=1)+
  geom_point(size=2.5)+
  theme_classic()



data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(mean = mean(x[[col]], na.rm=TRUE),
      sd = mad(x[[col]], na.rm=TRUE))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- rename(data_sum, c("mean" = varname))
 return(data_sum)
}


df3 <- data_summary(alldata, varname="mean", 
                    groupnames=c("organ", "timepoint"))


head(df3)
# Standard deviation of the mean
ggplot(df3, aes(x=timepoint, y=mean, group=organ, color=organ)) + 
   geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=0.2, position=position_dodge(0.3), size=1) +
    geom_line(position=position_dodge(0.3), size=1.5) + geom_point(position=position_dodge(0.3), size=4)+theme_classic()+
  geom_point(data=alldata, aes(x=timepoint, y=mean, group=organ),position=position_dodge(0.3) )




#T-tests
#0h vs 72h
t.test(samples$mean[samples$timepoint=="72h"], y = samples$mean[samples$timepoint=="0h"], paired=TRUE, alternative = "g")
#0h vs 24h
t.test(samples$mean[samples$timepoint=="24h"], y = samples$mean[samples$timepoint=="0h"], paired=FALSE, alternative = "g")





```




```{r}
sessionInfo()
```
